stitchfix/log_weasel

- lib/stitch_fix/log_weasel/railtie.rb
- spec/spec_helper.rb
- stitchfix-log_weasel.gemspec
The addresses an issue that @FreekingDean ran into while updating the `api_client` gem in Kingmob.
Tracker: https://www.pivotaltracker.com/story/show/145729071
Solution: Added the `combustion` gem so the Railtie gets loaded (and thus, tested) when specs are run.
> Add spec coverage for Railtie.

- README.md
- lib/stitch_fix/log_weasel.rb
- lib/stitch_fix/log_weasel/monkey_patches.rb
- lib/stitch_fix/log_weasel/pwwka.rb
- lib/stitch_fix/log_weasel/railtie.rb
- lib/stitch_fix/log_weasel/resque.rb
- lib/stitch_fix/log_weasel/resque_scheduler.rb
- lib/stitch_fix/log_weasel/tasks.rb
- lib/stitch_fix/log_weasel/version.rb
- spec/log_weasel/log_weasel_spec.rb
- spec/log_weasel/pwwka_spec.rb
- spec/log_weasel/resque_scheduler_spec.rb
- spec/log_weasel/resque_spec.rb
- stitchfix-log_weasel.gemspec
Nicola filed [an issue](https://github.com/stitchfix/log_weasel/issues/3) against Log Weasel where she was seeing static Log Weasel transaction IDs across multiple requests - which shouldn't happen. Each unit of work should be given a unique UUID, whether the work begins with a web request, API request, or a Resque job (scheduled or delayed). Additionally, Pwwka message handlers need to be able to pass along this UUID to processes kicked off in the handler (like a Resque job) so the transaction ID can be threaded through to all parties involved in processing the unit of work. 
I did a holistic reevaluation of Log Weasel, and found several issues:
1) LW transaction IDs for delayed Resque jobs (handled by Resque Scheduler) were not being properly set/managed. 
2) There was no _real_ LW …
> Bug/149199523 unique uuid for calls made from Resque [#149199523]

- lib/stitch_fix/log_weasel.rb
- spec/log_weasel/resque_scheduler_spec.rb
**Problem**
Some of our apps do not use resque_scheduler, and when log weasel is added to one of these projects, a `LoadError` is caused due to how log weasel requires resque_scheduler dependencies when it is initialized.
**Solution**
Only require resque_scheduler code in log weasel if resque scheduler is defined.
```
LoadError: cannot load such file -- resque/scheduler/env
/home/ubuntu/mobile-service/vendor/bundle/ruby/2.3.0/gems/stitchfix-log_weasel-1.1.0/lib/stitch_fix/log_weasel/resque_scheduler.rb:1:in `require'
/home/ubuntu/mobile-service/vendor/bundle/ruby/2.3.0/gems/stitchfix-log_weasel-1.1.0/lib/stitch_fix/log_weasel/resque_scheduler.rb:1:in `<top (required)>'
/home/ubuntu/mobile-service/vendor/bundle/ruby/2.3.0/gems/stitchfix-log_weasel-1.1.0/lib/stitch_fix/log_weasel.rb:6:in …
```
> Add guard to requires.

- README.md
These look to be remnants from the original source, before we forked.
Further reading: https://github.com/stitchfix/eng-wiki/blob/70938d18e44d240be12120f263885ebfd5bc0a33/technical-topics/log-weasel-configuration.md
> Includes stitchfix name in gem and module

- lib/stitch_fix/log_weasel/logger.rb
- lib/stitch_fix/log_weasel/version.rb
- stitchfix-log_weasel.gemspec
This addresses Issue #6. Copied here for convenience:
In Rails 5 they moved the #silence method to a concern. This can occasionally break things when other libraries expect it to be there (see stitchfix/playback#38).
Detect rails version and include LoggerSilence when applicable. This prevents downstream apps that use LogWeasel from having to care about this.
> Include LoggerSilence for apps running Rails >= 5.

- PULL_REQUEST_TEMPLATE.md
We have a Ruby Gem release process, but it is not always discoverable when merging a pull request in a gem.
Add a pull request template with a link to the gem release process and a checklist of the high-level release steps.
Please review the diff and merge this PR if it looks good.
Note that if there was an existing PR template for this gem, the goro process that opened this PR replaced the existing template with new content. In this case, it's up to you to reconcile the diff and combine any existing content with the updates in a way that makes sense for this gem.
> Add pull request template with gem release instructions

- lib/stitch_fix/log_weasel/transaction.rb
- spec/log_weasel/resque_spec.rb
- spec/log_weasel/transaction_spec.rb
- stitchfix-log_weasel.gemspec
Correlation IDs aren't lexicographically meaningful.
We want to Correlation IDs to be sortable by time. So we moved the app
id to be a suffix and updated the ID generator to use ULIDs which are
48 bits of timestamp and 80 bits of random.
Refs: https://stitchfix.atlassian.net/browse/RLO-28
Co-Authored-By: Adam Strickland <adam.strickland@stitchfix.com>
[Google Doc](https://docs.google.com/document/d/1wPn7M2HE2ghZJutWaMbctNcSroc-9r1FFdEUriYlxDc/edit)
[Jira ticket](https://stitchfix.atlassian.net/browse/RLO-28)
See the [gem release process](https://github.com/stitchfix/eng-wiki/blob/master/technical-topics/updating-gem-versions.md) for a detailed list, but the gist of it is:
> Update `log_weasel` to use ULIDs for IDs

- README.md
The logger configuration in Rails apps at Stitch Fix is different than vanilla Rails. The setup outlined in the README therefore does not apply to Stitch Fix Rails apps.
Add a link to the documentation on the eng-wiki on how to configure Log Weasel in Stitch Fix Rails apps.
«Brief description of how you solved the problem»
See the [gem release process](https://github.com/stitchfix/eng-wiki/blob/master/technical-topics/updating-gem-versions.md) for a detailed list, but the gist of it is:
> Add link to Stitch Fix documentation

- lib/stitch_fix/log_weasel/logger.rb
When upgrading to Rails 6, the following deprecation warning is emitted: 
```
DEPRECATION WARNING: Including LoggerSilence is deprecated and will be removed in Rails 6.1. Please use `ActiveSupport::LoggerSilence` instead (called from <top (required)> at /Users/srinivasrao/Documents/stitchfix/question-set-service/config/application.rb:22)
```
attempt to include `ActiveSupport::LoggerSilence` first if available, while still falling back to `LoggerSilence` for backwards compatibility.
> prefer non-deprecated module if available

- README.md
- lib/stitch_fix/log_weasel.rb
- lib/stitch_fix/log_weasel/monkey_patches.rb
- lib/stitch_fix/log_weasel/resque_scheduler.rb
- spec/log_weasel/resque_scheduler_spec.rb
LogWeasel logging is noisy, as there are some `puts` sprinkled into the codebase "put" there originally for debugging purposes. Extraneous logging increases our logging costs, so let's not log if we don't need to.
Add a `debug` configuration option, and only invoke these `puts` lines when `debug` is configured as truthy.
> Mute puts by adding debug configuration

- spec/spec_helper.rb
After a version upgrade to 1.2.0, Combustion started raising an error on log_weasel deploys:
https://github.com/stitchfix/log_weasel/commit/26a1a07d73737994c67b11e7794b3fa1bdf0d6ed
The reason for this is that we were initializing Combustion with `:active_support`, which was not a valid input (https://github.com/pat/combustion/blob/2cf632bcf6dae1db8a48dc3575c359af7f597ed6/lib/combustion.rb#L16-L29). 
Combustion started raising errors on invalid modules in 1.2.0.
ActiveSupport is always loaded by Combustion, as specified in their README: https://github.com/pat/combustion/tree/2cf632bcf6dae1db8a48dc3575c359af7f597ed6#configuring-which-rails-modules-should-be-loaded
> ActiveSupport and Railties are always loaded, as they're an integral part of Rails.
Remove the invalid `:active_support` …
> Fix invalid spec setup (passing :active_support to Combustion)

- README.md
- lib/stitch_fix/log_weasel/middleware.rb
- lib/stitch_fix/log_weasel/version.rb
- spec/log_weasel/middleware_spec.rb
https://github.com/stitchfix/csp-report-service/pull/39 did a proof of concept on ways to pull a log weasel transaction id out of parameters _instead of just from the headers_.  @almostwhitehat and @rdadlani are more of the experts in "why" this is - but my understanding is these requests will be coming from a user's browser, using built in CSP functionality so modifying headers for the request isn't possible, _but_ adding query strings are.  One of our front end apps would be responsible for generating and returning the value to be used by the browser as shown [here](https://github.com/stitchfix/doompatrol/pull/5/files#diff-55c5b7aecfb519d0e4880eaf2788eb6eR34-R36)
So `TL;DR` it would be nice - in this case - to be able to grab the "existing" transaction ID from the params of the request, …
> Adds ability to pull logweasel id from params

- lib/stitch_fix/log_weasel/middleware.rb
- spec/log_weasel/middleware_spec.rb
When pushing a developer defined trace_id through the system, we can only define it on the initial request, so much of our UI now does work on secondary ajax requests that you can't set the trace in a useful way for dev tests.
Similar to the log_weasel from params, we can allow from a cookie... Neither of these features is useful or desired in standard use, which is why they are disabled by default and have to be turned on with ENV vars `LOG_WEASEL_FROM_COOKIE=true`. This will pick up a trace from a cookie and allow it to be on the initial request as well as the ajax requests.
See the [gem release process](https://github.com/stitchfix/eng-wiki/blob/master/technical-topics/updating-gem-versions.md) for a detailed list, but the gist of it is:
> add support for cookie traces

- src/stitch_fix/__tests__/logWeaselTest.test.js
- src/stitch_fix/logWeasel.js
Log Weasel adds an extension to the Log Weasel ID that indicates the context in which the ID originated. For web requests, it uses `-WEB` as the extension. For Resque jobs, it uses `-RESQUE` as the extension. But for requests originating in javascript, we are currently using `-WEB`.
Update the extension to `-JS` for requests that originate from javascript.
See the [gem release process](https://github.com/stitchfix/eng-wiki/blob/master/technical-topics/updating-gem-versions.md) for a detailed list, but the gist of it is:
> Update LWID extension for JS

- README.md
- package.json
- src/stitch_fix/__tests__/__snapshots__/logWeaselTest.test.js.snap
- src/stitch_fix/__tests__/logWeaselTest.test.js
- src/stitch_fix/logWeasel.js
Because LW uses a singleton to track initialization state (the application name), any later initializations of LW can overwrite the original initialization values. Now that we are distributing components with LW in them, we are guaranteed to have multiple initializations. We already have 3 inits that overwrite themselves in KIUI – the app itself, ER, and the Graph API helper. So as the app runs, the supposedly universal app name is changed three times. This breaks the connection between the code a consumer of LW sets and the value of the header when sent, making it hard to infer what code sent what request.
Instead of enabling spooky action at a distance, we’ll make log weasel a simple function with no initialization. If people want to standardize the name they’re passing in they can …
> Avoid overwriting singleton init state when more than one user of LW exists in an application (Breaking change)

- index.d.ts
- package.json
- src/stitch_fix/generateId.d.ts
- src/stitch_fix/generateId.js
Although the JS package isn't written in TS, it's a pain for TS apps to add a module declaration file when they need to use it. The types also need to be exposed through packages like ER that are in TS, and are consumed by TS apps.
Expose a global TS module def. Check in a TS aware application that this works as expected when importing Log Weasel directly.
After merge:
> Add global type defs

- lib/stitch_fix/log_weasel.rb
- lib/stitch_fix/log_weasel/sidekiq.rb
- lib/stitch_fix/log_weasel/version.rb
- spec/log_weasel/log_weasel_spec.rb
- spec/log_weasel/sidekiq_spec.rb
- stitchfix-log_weasel.gemspec
We don't have any support in Log Weasel for maintaining the transaction ID through Sidekiq Jobs.
Add support similiar to that of Resque
Example of logs with log weasel trace id (all jobs started from a singular rake task): https://staging-stitchfix.datadoghq.com/logs?cols=&event&from_ts=1639668154099&index=&live=false&messageDisplay=inline&query=%40app.process_type%3Asidekiq+service%3Aproduct-catalog-service+%40log.log_weasel_trace_id%3A01FQ1XDBBSGB1KEN0XJ5CT0TVH-PRODUCTCATALOGSERVICE-SIDEKIQ&stream_sort=time%2Casc&to_ts=1639668241524
In conjunction with https://github.com/stitchfix/sidekiq_utils/pull/3
See the [gem release process](https://github.com/stitchfix/eng-wiki/blob/main/technical-topics/updating-gem-versions.md) for a detailed list, but the gist of it is:
> Add Sidekiq support for LogWeasel

- lib/stitch_fix/log_weasel/tasks.rb
- spec/log_weasel/log_weasel_spec.rb
- spec/log_weasel/pwwka_spec.rb
- stitchfix-log_weasel.gemspec
Tests were failing against Rails 7 because the `pwwka` library makes an unsupported (in Rails 7) call to `.parent` during initialization. 
```
Failure/Error: let(:publish_options) { Pwwka::PublishOptions.new(**options) }
NoMethodError:
undefined method `parent' for Combustion::Application:Class
Did you mean?  present?
/home/circleci/.rubygems/gems/railties-7.0.1/lib/rails/railtie.rb:226:in `method_missing'
/home/circleci/.rubygems/gems/pwwka-0.24.0/lib/pwwka/configuration.rb:55:in `app_id'
/home/circleci/.rubygems/gems/pwwka-0.24.0/lib/pwwka/publish_options.rb:16:in `initialize'
./spec/log_weasel/pwwka_spec.rb:62:in `new'
./spec/log_weasel/pwwka_spec.rb:62:in `block (5 levels) in <top (required)>'
./spec/log_weasel/pwwka_spec.rb:65:in `block (5 levels) in <top (required)>'
```
Replace …
> Replace pwwka with stitchfix-messaging

- lib/stitch_fix/log_weasel/tasks.rb
- spec/log_weasel/log_weasel_spec.rb
- spec/log_weasel/pwwka_spec.rb
- stitchfix-log_weasel.gemspec
Reverts stitchfix/log_weasel#44
With support for Rails 7 introduced in [pwwka](https://github.com/stitchfix/pwwka/releases/tag/v1.0.0), there's no need to migrate to a private dependency.
> Revert "Replace pwwka with stitchfix-messaging"

- stitchfix-log_weasel.gemspec
See issue #42 
There are probably a number of ways to exclude `src` from the gemspec files list, such as with a inverted regex pattern or a Git-specific glob like `git ls-files -- . ':!:src*'`. I chose an approach I thought would be less obfuscated.
Fixes #42
> Exclude JS src from gem files

- lib/stitch_fix/log_weasel/transaction.rb
- lib/stitch_fix/log_weasel/version.rb
- spec/log_weasel/transaction_spec.rb
Given that Stitch Fix has shared backend services for multiple front-end systems, it can be helpful to break out Datadog stats, metrics, and logs by the origin of a request. 
Example: for a client-facing functionality which is supported by Client Service, quickly knowing if a number of errors are coming from iOS, Android, or Web can narrow down if an issue is isolated to a particular front-end system.
We have two examples where this is used:
* [Financial Transaction Service](https://github.com/stitchfix/financial-transaction-service/blob/5fd2235c928ef32077588322cf08f5081000c4ca/lib/log_weasel_id.rb)
* [Client Service auth stats](https://github.com/stitchfix/client-service/blob/main/app/controllers/concerns/unified_auth_stats.rb)
We have another possible use coming up (stats from Client …
> Access origin of transaction

- spec/log_weasel/sidekiq_spec.rb
New build errors due to Sidekiq 7: https://app.circleci.com/pipelines/github/stitchfix/log_weasel/816/workflows/cc90c2e2-0acf-4ccc-b386-4d5beb2b44f9/jobs/6689/steps
The global `Sidekiq.client_middleware` and `Sidekiq.server_middleware` methods were removed. This only appears to impact how we are testing initialization. 
Fix access to `client_middleware` and `server_middleware`
See the [gem release process](https://github.com/stitchfix/eng-wiki/blob/main/technical-topics/updating-gem-versions.md) for a detailed list, but the gist of it is:
> Fix middleware access for Sidekiq 7

- .github/CODEOWNERS
app-platform owns most the Stitch Fix logging libraries, but not this one.
Add this repo to our collection
> Update CODEOWNERS: app-platform
